# Generated by Django 5.2.1 on 2025-07-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_mobile_user_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userotp',
            name='temp_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userotp',
            name='temp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userotp',
            name='temp_mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userotp',
            name='temp_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userotp',
            name='temp_username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
