# Generated by Django 5.2.1 on 2025-07-21 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userotp_is_admin_userotp_temp_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='userotp',
            name='temp_address',
        ),
        migrations.RemoveField(
            model_name='userotp',
            name='temp_email',
        ),
        migrations.RemoveField(
            model_name='userotp',
            name='temp_mobile_no',
        ),
        migrations.RemoveField(
            model_name='userotp',
            name='temp_password',
        ),
        migrations.RemoveField(
            model_name='userotp',
            name='temp_username',
        ),
    ]
